# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d570f0eea285367fdd752cd25bcf5a1e3911c66cd1f8a7236c04066191b0940f7af5154259e1d81c25dce002e10ef1d482f239a47575266a52137b3544f0d7ff
  bot_access_token: EAAUcv8rzD9kBAGQj3GMA7I8kBQ29RWoQzcEAZB9Dp3Bjn6qAmg6KFZAkCr7FpUWqIuiDdLEQKckPwIZB8ar2Qox3k9O3LKKHmtsWDhQMhOEfG9aVZAd8Jxs1JVJcOPQXshONqEqZBmRRGbPRBNCMJKqUnD88TQSk5slyJHW7pkAZDZD
  bot_app_secret: b37d061be68c77c7d919188f12f0bea0
  bot_verify_token: this_is_my_token

test:
  secret_key_base: 8958f376a2768d2fc3a7ae149007d9ca1906f1a58a00f0633f6edbba288de2a0106354253326c5ecb1bc18dd809f2f8a6a726e20288b3a48603fdbde39a0f627

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bot_access_token: <%= ENV["ACCESS_TOKEN"] %>
  bot_app_secret: <%= ENV["APP_SECRET"] %>
  bot_verify_token: <%= ENV["VERIFY_TOKEN"] %>
